#!/usr/bin/python3

import sys
import argparse
import urllib.request
import urllib.parse
import csv
import os
import logging

# The queries are documented here: https://github.com/roataway/web-ui/tree/master/src/data
QUERY_SEGMENTS = "http://overpass-api.de/api/interpreter?data=[out:json];relation%%20(%s)%%3B>>%%3Bway._%%3Bout%%20geom%%3B"
QUERY_STATIONS = "http://overpass-api.de/api/interpreter?data=[out:json];relation%%20(%s)%%3B>>%%3Bnode._%%20[public_transport%%3Dplatform]%%3Bout%%3B"

TEMPLATE_SEGMENTS = "route_%s_segments.json"
TEMPLATE_STATIONS = "route_%s_stations.json"

log = logging.getLogger('route')

def get_url(url):
    """Retrieve the body of a page given by the URL
    :param url: str
    :returns: str, the payload"""
    with urllib.request.urlopen(url) as f:
        return f.read().decode('utf-8')


def save_route(upstream_id, osm_relation, target_path):
    """Save a given route to a JSON file.
    :param upstream_id: int, the identifier of the route in the upstream
                        tracking system.
    :param osm_relation: int, the identifier of the route in OpenStreetMap.
    :param target_path: str, directory to save to, the file name follows the
                        conventions given in the src/data.
    :returns: None"""
    segments = get_url(QUERY_SEGMENTS % osm_relation)
    stations = get_url(QUERY_STATIONS % osm_relation)


    with open(os.path.join(target_path, TEMPLATE_SEGMENTS % upstream_id), 'w') as f:
        f.write(segments)

    with open(os.path.join(target_path, TEMPLATE_STATIONS % upstream_id), 'w') as f:
        f.write(stations)


def process_csv(csv_path, target_path):
    """Retrieve and store all routes in a given CSV file, the CSV header is
    `id_upstream, name_concise, name_long, osm_relation`
    :param csv_path: str, path to CSV with list of routes
    :param target_path: str, directory to save files to"""
    with open(csv_path) as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            log.info('Processing route %s, `%s`', row['name_concise'], row['name_long'])
            save_route(row['id_upstream'], row['osm_relation'], target_path)




if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG,
                        format='%(levelname)5s - %(message)s')
    parser = argparse.ArgumentParser(description='Retrieve route-related meta-data from OpenStreetMaps')
    parser.add_argument("--csv", help="Get all routes specified in a CSV file")
    parser.add_argument("--dst", help="Destination directory where to write the data",
                        default=".")
    parser.add_argument("-r", "--route", help="Retrieve a specific route, identified by its OpenStreetMap relation id. This overrides --csv.")

    args = parser.parse_args()

    if args.csv:
        log.info('Processing all routes from %s', args.csv)
        process_csv(args.csv, args.dst)
    elif args.route:
        log.info('Processing single route specified by relation %s', args.route)
        save_route(args.route, args.route, args.dst)
    else:
        parser.print_help()
        sys.exit()

    log.info('Done')
